### ISSUE TITLE
Update Windows development instructions

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-docs#152] opened 2019-11-10 19:56 UTC
@TamorHaabmets reports:

> I tried it out and i had some permission problems when running grunt. Error message was:
tar EPERM: operation not permitted, futime
> These two commands helped me out (insert them in your linux home directory).
> sudo umount /mnt/c
> sudo mount -t drvfs C: /mnt/c -o metadata,uid=1000,gid=1000,umask=22,fmask=111
> More info:
https://stackoverflow.com/questions/56457844/tar-eperm-operation-not-permitted-futime

Investigate and update [the instructions](https://github.com/medic/medic-docs/blob/master/development/using-windows.md) as needed.

cc @SCdF

**Comment by SCdF** [comment] 2019-11-12 18:55
@TamorHaabmets I'm not able to reproduce this locally, and so it's hard for me to verify the instructions.

I'm wondering if it's because of a specific version of something that you're using, or perhaps becuase of a way your Windows 10 is setup. Unfortunately I'm not that versed in Windows.

Could you provide me with:
 - Your Windows version (hit Win key, type "about", hit enter, scroll down to see "Version" in "Windows Specifications"
 - Your Ubuntu WSL version (hit Win key, type "Ubuntu", Windows should give you an option to see it's "App settings", version is in there)
 - `uname -a` from inside the WSL image (ie from bash)
 - `cat /etc/fstab` from inside the WSL image

Thanks!

**Comment by kennsippell** [comment] 2019-12-13 00:48
@yrimal You just got our stack running on Windows + WSL. We discussed how your learnings with WSL could be useful to contribute into the documentation. 

Here is an example issue which you might have encountered and have a fix for.

**Comment by kennsippell** [comment] 2020-02-15 15:44
Fixed by https://github.com/medic/medic-docs/pull/170. Please re-activate if you're still having trouble on Windows.

**Closed by kennsippell** 2020-02-15 15:44 UTC
Labels: documentation
